DROP TABLE IF EXISTS #encounter_count;
SELECT 
	PERSON_ID AS patid, 
	COUNT(ENC_ID) enc_count
INTO #encounter_count
FROM @SCHEMA.@ENCOUNTERS
WHERE ADATE >= '2017-6-1' AND ADATE < '2018-6-1'
GROUP BY PERSON_ID;
